#!/usr/bin/env bash
# ============================================================================
# Garage Initialization Script
# ============================================================================
# Creates buckets and keys for image storage (ADR-057)
#
# Usage:
#   ./scripts/garage/init-garage.sh
#
# Environment Variables (optional, from .env):
#   GARAGE_RPC_SECRET      - RPC secret for cluster coordination
#   GARAGE_S3_ENDPOINT     - S3 API endpoint (default: http://localhost:3900)
#   GARAGE_BUCKET          - Bucket name (default: kg-storage)
#
# Note: Application retrieves credentials from encrypted key store (ADR-031)
#       Configure via: ./scripts/setup/initialize-platform.sh (option 7)
# ============================================================================

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Load environment variables
if [ -f .env ]; then
    source .env
fi

GARAGE_ENDPOINT="${GARAGE_S3_ENDPOINT:-http://localhost:3900}"
GARAGE_BUCKET="${GARAGE_BUCKET:-kg-storage}"

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Garage Initialization${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if Garage container is running
echo -e "${YELLOW}→ Checking Garage container...${NC}"
if ! docker ps | grep -q knowledge-graph-garage; then
    echo -e "${RED}✗ Garage container not running${NC}"
    echo -e "${YELLOW}  Run: docker-compose up -d garage${NC}"
    echo -e "${YELLOW}  Or start all services: docker-compose up -d${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Garage container running${NC}"
echo ""

# Wait for Garage to be ready
echo -e "${YELLOW}→ Waiting for Garage to be ready...${NC}"
MAX_RETRIES=30
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if docker exec knowledge-graph-garage /garage status > /dev/null 2>&1; then
        echo -e "${GREEN}✓ Garage is ready${NC}"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
        echo -e "${RED}✗ Garage failed to become ready after ${MAX_RETRIES} attempts${NC}"
        exit 1
    fi
    sleep 1
done
echo ""

# Assign role to node if not already assigned (required for bucket operations)
echo -e "${YELLOW}→ Checking node role assignment...${NC}"
NODE_ID=$(docker exec knowledge-graph-garage /garage status 2>&1 | grep "NO ROLE ASSIGNED" | awk '{print $1}')

if [ -n "$NODE_ID" ]; then
    echo -e "${BLUE}  Node ${NODE_ID} needs role assignment${NC}"

    # Assign role with 10GB capacity
    docker exec knowledge-graph-garage /garage layout assign "$NODE_ID" -z dc1 -c 10G > /dev/null 2>&1

    # Apply layout
    docker exec knowledge-graph-garage /garage layout apply --version 1 > /dev/null 2>&1

    echo -e "${GREEN}✓ Node role assigned and layout applied${NC}"
else
    echo -e "${BLUE}  Node role already assigned${NC}"
fi
echo ""

# Create bucket if it doesn't exist
echo -e "${YELLOW}→ Creating '${GARAGE_BUCKET}' bucket...${NC}"
if docker exec knowledge-graph-garage /garage bucket info "${GARAGE_BUCKET}" > /dev/null 2>&1; then
    echo -e "${BLUE}  Bucket '${GARAGE_BUCKET}' already exists${NC}"
else
    docker exec knowledge-graph-garage /garage bucket create "${GARAGE_BUCKET}" > /dev/null 2>&1
    echo -e "${GREEN}✓ Bucket '${GARAGE_BUCKET}' created${NC}"
fi
echo ""

# Create or retrieve API key
echo -e "${YELLOW}→ Setting up API key...${NC}"
KEY_NAME="kg-api-key"

# Check if key exists
TEMP_CREDS="/tmp/garage-credentials.txt"

if docker exec knowledge-graph-garage /garage key info "${KEY_NAME}" > /dev/null 2>&1; then
    echo -e "${BLUE}  Key '${KEY_NAME}' already exists${NC}"

    # Check if credentials file exists from previous run
    if [ -f "$TEMP_CREDS" ]; then
        echo -e "${BLUE}  Credentials file found: ${TEMP_CREDS}${NC}"
        echo -e "${YELLOW}  Run initialize-platform.sh option 7 to store in encrypted database${NC}"
    fi
else
    # Create key and capture credentials (shown only once)
    KEY_OUTPUT=$(docker exec knowledge-graph-garage /garage key create "${KEY_NAME}" 2>&1)
    echo -e "${GREEN}✓ Key '${KEY_NAME}' created${NC}"

    # Save credentials to temp file for configure_garage to auto-load
    # This is a bootstrap mechanism - file will be deleted after encryption storage
    KEY_ID=$(echo "$KEY_OUTPUT" | grep "Key ID:" | awk '{print $3}')
    SECRET_KEY=$(echo "$KEY_OUTPUT" | grep "Secret key:" | awk '{print $3}')

    if [ -n "$KEY_ID" ] && [ -n "$SECRET_KEY" ]; then
        TEMP_CREDS="/tmp/garage-credentials.txt"
        cat > "$TEMP_CREDS" << EOF
# Garage API credentials - auto-generated by init-garage.sh
# These will be automatically loaded by initialize-platform.sh option 7
# File will be deleted after secure storage in encrypted database
GARAGE_ACCESS_KEY_ID=$KEY_ID
GARAGE_SECRET_ACCESS_KEY=$SECRET_KEY
EOF
        chmod 600 "$TEMP_CREDS"  # Readable only by owner
        echo -e "${BLUE}  Credentials saved to: ${TEMP_CREDS}${NC}"
    fi
fi
echo ""

# Grant read/write permissions to bucket
echo -e "${YELLOW}→ Granting bucket permissions...${NC}"
docker exec knowledge-graph-garage /garage bucket allow \
    --read --write \
    --key "${KEY_NAME}" \
    "${GARAGE_BUCKET}" > /dev/null 2>&1
echo -e "${GREEN}✓ Permissions granted (read/write)${NC}"
echo ""

# Display bucket info
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ Garage initialization complete${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}Bucket Information:${NC}"
echo -e "  Name:       ${GARAGE_BUCKET}"
echo -e "  Policy:     Private (authentication required)"
echo -e "  Endpoint:   ${GARAGE_ENDPOINT}"
echo ""
echo -e "${BLUE}API Key Information:${NC}"
echo -e "  Key Name:   ${KEY_NAME}"
echo ""
echo -e "${YELLOW}To retrieve access credentials, run:${NC}"
echo -e "  docker exec knowledge-graph-garage /garage key info ${KEY_NAME}"
echo ""
echo -e "${YELLOW}Configure credentials in the system:${NC}"
echo -e "  ./scripts/setup/initialize-platform.sh (option 7)"
echo ""
