-- Migration 046: Annealing Proposals (ADR-200 Phase 3b)
-- Stores promotion and demotion proposals generated by the annealing worker.
-- Proposals are reviewed by humans before execution (HITL pattern).

-- Create annealing proposals table
CREATE TABLE IF NOT EXISTS kg_api.annealing_proposals (
    id SERIAL PRIMARY KEY,
    proposal_type VARCHAR(20) NOT NULL CHECK (proposal_type IN ('promotion', 'demotion')),
    ontology_name VARCHAR(200) NOT NULL,
    anchor_concept_id VARCHAR(100),       -- For promotions: concept proposed for elevation
    target_ontology VARCHAR(200),          -- For demotions: suggested absorption target
    reasoning TEXT NOT NULL,
    mass_score NUMERIC(10,4),
    coherence_score NUMERIC(10,4),
    protection_score NUMERIC(10,4),
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'rejected', 'expired')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at_epoch INT NOT NULL DEFAULT 0,
    reviewed_at TIMESTAMPTZ,
    reviewed_by VARCHAR(100),
    reviewer_notes TEXT,
    expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '7 days')
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_annealing_proposals_status
    ON kg_api.annealing_proposals(status);
CREATE INDEX IF NOT EXISTS idx_annealing_proposals_ontology
    ON kg_api.annealing_proposals(ontology_name);

-- Record migration
INSERT INTO public.schema_migrations (version, name)
VALUES (46, 'annealing_proposals')
ON CONFLICT (version) DO NOTHING;
